### ISSUE TITLE
[Issue] System Incompatibility

### ISSUE THREAD

**Issue by TheKillingJay** [earlSt1/vtt-navigation-presets#1]
Hey, when I saw this module I instantly fell in love because I already use its cousins Compendium Folder and Macro Folder. However, this one is not working for pf1e where the other ones are, with no other modules. It did work for 5e. I was wondering if there were something you might be aware of that could be changed to increase compatibility. 

I am definitely not asking you to go dig deep into another system; just wondering if it were possible its a super minor thing you could change really quick. If not, the world does not end.

Thanks for your time!

**Comment by earlSt1** [comment]
Hi, this was an oversight after porting some Compendium Folders code to this project. This will be fixed in the next release.

**Comment by earlSt1** [comment]
Issue now fixed in v1.0.4
