### ISSUE TITLE
Players can no longer see presets

### ISSUE THREAD

**Issue by CharlesHunter** [earlSt1/vtt-navigation-presets#11]
I created a blank 5E world to try and troubleshoot the issue.

I created 4 presets: 
- EmptyPreset (contains no maps)
- HiddenPreset (contains 1 map hidden from players)
- UsablePreset (contains 1 map available to players)
- UsablePreset2 (contains 1 map available to players)

As a GM, I could see and edit all presets.
As a player, I could not see the presets in any browser.

I restarted the game world.
As a player, I still could not see the presets in any browser.

**Comment by CharlesHunter** [comment]
I get this console error when logging in as a user:

`Uncaught (in promise) TypeError: game.scenes.get(...) is undefined
[Detected 2 packages: navigation-presets, lib-wrapper]
    getPresets http://192.168.1.202:23401/modules/navigation-presets/navigation-presets.js:553
    getPresets http://192.168.1.202:23401/modules/navigation-presets/navigation-presets.js:552
    getPresets http://192.168.1.202:23401/modules/navigation-presets/navigation-presets.js:551
    <anonymous> http://192.168.1.202:23401/modules/navigation-presets/navigation-presets.js:600
    _call http://192.168.1.202:23401/modules/lib-wrapper/lib-wrapper.js line 1 > eval:4
    call http://192.168.1.202:23401/scripts/foundry.js:179
    _render http://192.168.1.202:23401/scripts/foundry.js:2104
`

**Comment by earlSt1** [comment]
Hi, I tried to replicate this scenario but am not getting any errors as a player. 
Which scene do you currently have active? Did you delete any scenes after you configured the presets?

**Comment by earlSt1** [comment]
Fixed in 1.1.0
