### ISSUE TITLE
Selecting a token causes the Navigation bar to briefly expand

### ISSUE THREAD

**Issue by IndigoGnat** [earlSt1/vtt-navigation-presets#3]
Whenever I select or unselect a token, the navigation bar flickers, showing all of the scenes before returning to the currently selected presets.

**Comment by earlSt1** [comment]
Hi, unfortunately the hook responsible for rendering the navigation bar (which navigation presets utilises), can update quite a few times. I've noticed this happens a bit more often when i use the Calendar/Weather mod and sync the time of day + weather to the scene.

I think it's any module that may change the settings on the scene may cause this, although I havent heard of anyone experiencing this issue before. Can you update this with a list of modules you're using?

**Comment by IndigoGnat** [comment]
I dug into the code a bit and that's exactly what's happening.  It doesn't have any issues if it's the only module loaded so it's a conflict caused by other modules.  Hiding the navigation bar solves the problem, though.  I really only need it open when I'm navigating scenes.

But if you want my help figuring this out, I'm more than happy to provide whatever you need.  

Or, you can just close this out with the solution being "don't use a hundred modules and/or hide the navigation bar"

Here is my active module list:
resourcesplus--v1.6.2;
about-time--v0.1.59;
adventure-import-export--v0.5.7;
animated-spell-effects--v0.6.0;
autocomplete-whisper--v0.3.0;
backgroundless-pins--v1.2.0;
betterrolls5e--v1.2.0;
better-text-drawings--v1.0.4.2;
calendar-weather--v3.1.1;
coloredeffects--v0.0.6;
combat-carousel--v0.1.3;
combat-enhancements--v0.1.3;
combat-utility-belt--v1.3.6;
CommunityLighting--v0.3.1;
compact-beyond-5e-sheet--v0.10.2;
compendium-browser--v0.3.1;
compendium-folders--v2.1.2;
ConditionIconHoverZoom--v0.3;
conditions5e--v0.4.5.7;
cone-measurement-angle--v0.1.9;
custom-css--v1.1.3;
custom-journal--v1.2.1;
cycle-token-stack--v0.5.4;
dice-so-nice--v3.2.0;
dice-tooltip--v1.0.8;
dndbeyond-character-sheet--v1.5.1;
dndbeyond-npc-sheet--v1.0.0;
dragupload--v1.5.1;
Dynamic-Effects-SRD--v3.0.3;
dynamic-illumination--v0.7.7;
easy-target--v2.7;
fa-dm-screen--v0.4.1;
forien-copy-environment--v1.1.1;
forien-custom-fonts--v0.1.3;
forien-quest-log--v0.5.1;
forien-unidentified-items--v0.2.3;
foundry_community_macros--v0.29;
fxmaster--v0.9.8;
gm-notes--v0.3;
token-drag-visibility--v1.1.1;
illandril-chat-enhancements--v1.0.3;
journal-templates--v0.3.0;
lessfog--v0.7.1;
LetterTokens--v1.0.2;
colorsettings--v2.5.7;
lib-wrapper--v1.0.5.2;
lootsheetnpc5e--v2.2.0;
_mathjs--v7.5.1-fvtt2;
minor-qol--v0.1.77;
module-settings-sorter--v0.1;
monsterblock--v2.3.0;
mountup--v3.0.1;
multilevel-tokens--v1.3.4;
mwpm--v0.4.0;
navbar-tweaks--v1.0.4.2;
navigation-presets--v1.0.5;
noback--v0.0.2;
npcgen--v0.1.6;
parallaxia--v0.2.13;
perfect-vision--v1.2.7;
permission_viewer--v0.8;
personalmarkers--v1.0.6;
pin-cushion--v1.1.4;
pin-fixer--v0.1.4;
pings--v1.2.10;
plutonium--v1.15.1;
popout--v1.0;
roofs--v0.1.1;
rounded-distance-for-measured-templates--v0.2.0;
smip-compendium--v0.4.0;
searchanywhere--v2.0.4;
selectiveshow--v1.1;
select-tool-everywhere--v1.1.1;
ShowDragDistance--v2.2.3;
foundryvtt-show-notes--v0.3;
sidebar-aesthetics--v0.2.1;
_sortablejs--v1.10.2-fvtt1;
spellbook-master--v0.0.2;
statuscounter--v2.0.1;
swade-toolkit--v1.0.0;
target-enhancements--v0.9.5;
forge-vtt--v1.6;
furnace--vv2.6.0;
tidy5e-sheet--v0.3.5;
tidy-ui_game-settings--v0.1.21;
token-action-hud--v0.9.23;
token-auras--v1.7;
token-chat-link--v1.1.0;
tokenmagic--v0.4.4;
token-mold--v2.10.1;
token-tooltip--v1.3.4;
token-tooltip-alt--v2.0.17;
token-vision-tweaks--v1.3.1.2;
torch--v1.1.4;
turnAlert--v1.5.1;
vtta-dndbeyond--v3.3.4;
vtta-iconizer--v2.1.12;
vtta-tokenizer--v2.2.1;
WallCutter--v1.1.0;

**Comment by earlSt1** [comment]
yeah I'll go ahead and close this one. it's more of a limitation of how the navigation bar hook is handled in core. Hiding the navigation bar is a nice workaround though ill keep that in mind for the future. Thanks for raising this though :)
