### ISSUE TITLE
Is it possible to get this menu enabled for players as well?

### ISSUE THREAD

**Issue by Charles082986** [earlSt1/vtt-navigation-presets#5]
We have a lot of maps set up for individual player navigation within our campaign.  This module does everything I need, only it doesn't work for players.

**Comment by earlSt1** [comment]
Sure! I wrote this mainly because as a GM managing scenes was a big pain, but hadn't considered players with a lot of scenes to navigate to.

I'll bundle this feature into the next release, shouldn't take too long to implement.

**Comment by earlSt1** [comment]
Added in v1.0.6
