### ISSUE TITLE
[QUESTION] Compatability with DF Scene Enhancer (and other Scenes-altering mods)?

### ISSUE THREAD

**Issue by Shuggaloaf** [earlSt1/vtt-navigation-presets#6]
Hi just wondering if you knew of any conflicts with with DF Scene Enhancer specifically, but thought I'd ask about other known conflicts as well. Hopefully this is the appropriate place to ask.

**Comment by earlSt1** [comment]
I haven't tested it specifically, but I also havent heard of any compatibility issues with other scene mods. This module only affects the navigation bar at the top, and a cursory glance at the DF Scene Enhancer I can't imagine there being any conflicts.

**Comment by Shuggaloaf** [comment]
Awesome! That's good enough for me to give it a go. 

I appreciate you taking a look. Thanks for the response and the great mods (ESPECIALLY THE FOLDER MODS)!
